trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'bstack-conn'
      browserstackLocal: true
      bsLocalOptions: 'forceLocal'
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test -P single_web'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
  
  - task: BrowserStackResults@1
    inputs:
      browserstackProduct: 'automate'